# Generated by Django 5.0.6 on 2024-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0002_remove_team_users_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['first_name', 'last_name', 'email']},
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
